### ISSUE TITLE
Crear docker

### ISSUE THREAD

**Issue by martinszy** [martinszy/panamasearch#3]
Crear un docker para que el sistema se pueda ejecutar de forma sencilla en cualquier sistema.

**Comment by martinszy** [comment]
Ya hubo avance en esto, hay que testearlo @cubetto

**Comment by martinszy** [comment]
Hay que agregar instrucciones del docker al readme

**Comment by martinszy** [comment]
Paso 1: Instalar docker https://docs.docker.com/engine/installation/
Paso 2: docker run [paquete] ?

**Comment by martinszy** [comment]
docker run -p 3000:3000 -d cubetto/panamasearch:v1

**Comment by gerfranc** [comment]
buenas, interesado en testearlo. 
Corri el dock.. bajo perfecto todo lo que tenia que bajar..  pero despues no lo enceuntro en ningun puerto del localhost, no deberia estar en http://localhost:3000? o estoy haciendo cualquier ganzada?

saludos!

**Comment by martinszy** [comment]
A mi me funcionó con docker run -d -p 30001:5000 cubetto/panamasearch:v1
Creo que tienen que ser distintos los numerso de puerto. El publico es el primero.
Estas haciendolo bien.

De hecho ya hay una instancia publica http://panamasearch.fcabierto.org:30001/

**Comment by marianoferle** [comment]
* Por el momento solo pude hacer que cargue el csv si se carga por FILE UPLOAD buscando el archivo.

Nueva function:    imprime datos en tabla al cargar CSV:




   // archivo .js
   //------------------load file------------------------------
    $("#resultCSV").change(function(e){

        var ext = $("input#resultCSV").val().split(".").pop().toLowerCase();

        if($.inArray(ext, ["csv"]) == -1){
            alert('Upload CSV');
            return false;
        }
        
        if (e.target.files != undefined){
            var reader = new FileReader();
            //-----------------
            reader.onload = function(e){
                var csvval=e.target.result.split("\n");              
                for(var j=0;j<csvval.length-1;j++){
                    var csvvalue=csvval[j].split(",");    
                    
                    //set de la cantidad de datos por persona
                    $("#resultadoCSV table").append(
                        "<tr>"+
                        "<td>"+csvvalue[0]+"</td>"+
                        "<td>"+csvvalue[1]+"</td>"+
                        "<td>"+csvvalue[2]+"</td>"+
                        "<td>"+csvvalue[3]+"</td>"+
                        "</tr>"
                    );              
                } 
            };
            //----------------------
            reader.readAsText(e.target.files.item(0));
        }
        return false;
    });
    //---------------------------------







<div id="contResp" class="contPage col-sm-12">
                  <h1>Subir Archivo CSV con resultados</h1>
                  <input type="file" name="resultCSV" id="resultCSV">  
                  <div id="resultadoCSV">
                  <table>
                    
                  </table>
                  </div> 
</div>

**Comment by gerfranc** [comment]
Estoy igual.. por el momento solo upload, y quedan en "pending" los archivos. Lo bueno es que lo pude hacer correr localmente (pasaba que el localhost no era el 127.0.0.1 o "localhost", sino 0.0.0.0).

**Comment by marianoferle** [comment]
function -->  toma la url al hacer click en "ver"
* usa la libreria papaparse:

----------------------------funciona en un SERVER - PHP-------------------



<script src="http://papaparse.com/resources/js/papaparse.js"></script>





//-------javascript:--------

 function verCSV(url_){       

      Papa.parse(url_, {
        download: true,
        complete: function(results){ 
      
            for(var i=0;i<results.data.length;i++){ 

                   $("#resultadoCSV table").append(
                        "<tr>"+
                        "<td>"+results.data[i][0]+"</td>"+
                        "<td>"+results.data[i][1]+"</td>"+
                        "<td>"+results.data[i][2]+"</td>"+
                        "<td>"+results.data[i][3]+"</td>"+
                        "</tr>"
                    );
            }                        
          }        
      });







 
<div id="verCSV" onclick="javascript:verCSV('lista.csv')">ver</div>

<div id="resultadoCSV">
  <table>
                    
 </table>
</div>
